{{- if eq .Values.app_settings.schema_registry.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avro-schema-registry
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: {{ .Values.images.schema_registry.image }}:{{ .Values.images.schema_registry.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka-1.kafka:9092,PLAINTEXT://kafka-2.kafka:9092,PLAINTEXT://kafka-3.kafka:9092
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8080
---
apiVersion: v1
kind: Service
metadata:
  name: avro-schema-registry
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: avro-schema-registry
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
{{- end }}