name: Build Module

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Select a Gradle module to build.'
        required: true
        type: choice
        options:
          - continuum-api-server
          - continuum-avro-schemas
          - continuum-base
          - continuum-commons
          - continuum-frontend
          - continuum-knime-base
          - continuum-message-bridge
          - continuum-springboot-starter-worker
          - continuum-worker
          - workers/continuum-base-worker

jobs:
  build-module:
    uses: ./.github/workflows/generic-module-builder.yml
    with:
      module-name: ${{ github.event.inputs.module }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
